envVarGroups:
  - name: hp-envs
    envVars:
      - key: DB_POOL
        value: 10

databases:
  - name: hp-db
    databaseName: hp_webstore_production
    user: hp_webstore_user
    plan: basic-1gb
    diskSizeGB: 10

services:
  - type: web
    name: hp-web
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    preDeployCommand: bin/rails db:migrate && bin/rails db:seed
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hp-db
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: hp-redis
          property: connectionString

  - type: worker
    name: hp-worker
    runtime: ruby
    plan: standard
    buildCommand: bin/render-build.sh
    startCommand: bundle exec sidekiq
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hp-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: hp-redis
          property: connectionString
      - key: REDIS_CACHE_URL
        fromService:
          type: keyvalue
          name: hp-redis-cache
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - fromGroup: hp-envs

  - type: keyvalue
    name: hp-redis
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

  - type: keyvalue
    name: hp-redis-cache
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: allkeys-lru
